In [21]:
# Install pip packages from requirements.txt into this current Jupyter kernel
import sys
!{sys.executable} -m pip install -r requirements.txt
import pandas as pd

Requirement already satisfied: nltk in /home/linuxbrew/.linuxbrew/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (3.7)
Requirement already satisfied: numpy in /home/cxwudi/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (1.22.2)
Requirement already satisfied: pandas in /home/cxwudi/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (1.4.1)
Requirement already satisfied: pyspellchecker in /home/linuxbrew/.linuxbrew/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (0.7.0)
Requirement already satisfied: emoji in /home/linuxbrew/.linuxbrew/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (2.2.0)
Requirement already satisfied: regex>=2021.8.3 in /home/linuxbrew/.linuxbrew/lib/python3.10/site-packages (from nltk->-r requirements.txt (line 1)) (2022.9.13)
Requirement already satisfied: click in /home/cxwudi/.local/lib/python3.10/site-packages (from nltk->-r requirements.txt (line 1)) (8.0.4)
Requirement already satisfied: joblib in /home/linuxbrew/.linuxbrew/lib/python3.10/site-packages (from nltk->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: tqdm in /home/linuxbrew/.linuxbrew/lib/python3.10/site-packages (from nltk->-r requirements.txt (line 1)) (4.64.1)
Requirement already satisfied: pytz>=2020.1 in /home/cxwudi/.local/lib/python3.10/site-packages (from pandas->-r requirements.txt (line 3)) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/cxwudi/.local/lib/python3.10/site-packages (from pandas->-r requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: six>=1.5 in /home/cxwudi/.local/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas->-r requirements.txt (line 3)) (1.16.0)

## Import

In [22]:
raw_dataset = pd.read_csv('../data/authors_dataset.csv')
raw_dataset

,date,id,no.Comments,score,upvote ratio,ups,downs,title,selftext,tag,...,Unnamed: 217,Unnamed: 218,Unnamed: 219,Unnamed: 220,Unnamed: 221,Unnamed: 222,Unnamed: 223,Unnamed: 224,Unnamed: 225,Unnamed: 226
0,2019-08-28 14:14:32,cwle38,48,637,0.98,637,0,"For anyone who's ever edited a video ever, enjoy.",NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-07-03 19:02:44,c8s3x2,15,448,0.97,448,0,Media Offline,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-06 15:30:11,ekvldh,51,424,0.96,424,0,Adobe Premiere youtuber starterpack.,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-03-27 14:29:08,fpxv8h,24,360,0.94,360,0,Just me?,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-02-26 18:00:17,f9x942,60,300,0.98,300,0,Monster of a weekly project done ðŸ˜…,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,2/9/20 18:09,f1cfwr,3,4,1.00,4,0,Looking for suggestions on my dilema,"Hello,I am wanting to make a excel spreadsheet...",0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1910,2/3/20 20:41,eydk1i,4,3,0.81,3,0,Seeking help with calculating future date,"I'm learning Excel as I go here, so I'm starti...",0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1911,12/20/19 21:21,edg9ol,4,5,1.00,5,0,Excel for the gym,I'm trying to put a gym routine on excel just ...,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1912,12/10/19 16:25,e8ssxt,2,3,0.81,3,0,Color Formatting,Is there anyway I can change the color of a ce...,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1913,3/29/20 5:05,fr0bua,1,3,1.00,3,0,Formulas/Graphs,"""Greetings!! I hope all is well. I wanted to k...",0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Preprocessing

In [23]:
from modules.preprocessing import preprocessing_df
preprocessed_dataset = preprocessing_df(raw_dataset)
preprocessed_dataset

,date,id,no.Comments,score,upvote ratio,ups,downs,title,selftext,tag,comments
0,2019-08-28 14:14:32,cwle38,48,637,0.98,637,0,"For anyone who's ever edited a video ever, enjoy.",NaN,0,[]
1,2019-07-03 19:02:44,c8s3x2,15,448,0.97,448,0,Media Offline,NaN,1,[]
2,2020-01-06 15:30:11,ekvldh,51,424,0.96,424,0,Adobe Premiere youtuber starterpack.,NaN,0,[]
3,2020-03-27 14:29:08,fpxv8h,24,360,0.94,360,0,Just me?,NaN,0,[]
4,2020-02-26 18:00:17,f9x942,60,300,0.98,300,0,Monster of a weekly project done ðŸ˜…,NaN,0,[]
...,...,...,...,...,...,...,...,...,...,...,...
1909,2/9/20 18:09,f1cfwr,3,4,1.00,4,0,Looking for suggestions on my dilema,"Hello,I am wanting to make a excel spreadsheet...",0,[]
1910,2/3/20 20:41,eydk1i,4,3,0.81,3,0,Seeking help with calculating future date,"I'm learning Excel as I go here, so I'm starti...",0,[]
1911,12/20/19 21:21,edg9ol,4,5,1.00,5,0,Excel for the gym,I'm trying to put a gym routine on excel just ...,2,[]
1912,12/10/19 16:25,e8ssxt,2,3,0.81,3,0,Color Formatting,Is there anyway I can change the color of a ce...,2,[]
1913,3/29/20 5:05,fr0bua,1,3,1.00,3,0,Formulas/Graphs,"""Greetings!! I hope all is well. I wanted to k...",0,[]

**WARNING**: The clock block will take 6 minutes to run, even with AMD Ryzen 9 5950x.

In [24]:
from modules.preprocessing import proprocessing_text
tokenized_dataset = proprocessing_text(preprocessed_dataset)

In [25]:
from functools import reduce
tokenized_dataset["merged_comments"] = tokenized_dataset["comments"].apply(lambda x: reduce(lambda a, b: a + b, x, []))
tokenized_dataset

,date,id,no.Comments,score,upvote ratio,ups,downs,title,selftext,tag,comments,merged_comments
0,2019-08-28 14:14:32,cwle38,48,637,0.98,637,0,"[anyone, ever, edit, video, ever, enjoy]",[],0,[],[]
1,2019-07-03 19:02:44,c8s3x2,15,448,0.97,448,0,"[medium, offline]",[],1,[],[]
2,2020-01-06 15:30:11,ekvldh,51,424,0.96,424,0,"[adobe, premiere, youtube, starterpack]",[],0,[],[]
3,2020-03-27 14:29:08,fpxv8h,24,360,0.94,360,0,[],[],0,[],[]
4,2020-02-26 18:00:17,f9x942,60,300,0.98,300,0,"[monster, weekly, project]",[],0,[],[]
...,...,...,...,...,...,...,...,...,...,...,...,...
1909,2/9/20 18:09,f1cfwr,3,4,1.00,4,0,"[look, suggestion, dilemma]","[hello, want, make, excel, spreadsheet, docume...",0,[],[]
1910,2/3/20 20:41,eydk1i,4,3,0.81,3,0,"[seek, help, calculate, future, date]","[learn, excel, go, start, something, hopefully...",0,[],[]
1911,12/20/19 21:21,edg9ol,4,5,1.00,5,0,"[excel, gym]","[try, put, gym, routine, excel, phone, instead...",2,[],[]
1912,12/10/19 16:25,e8ssxt,2,3,0.81,3,0,"[color, formatting]","[anyway, change, color, cell, information, giv...",2,[],[]
1913,3/29/20 5:05,fr0bua,1,3,1.00,3,0,"[formulas, graphs]","[greeting, hope, well, want, know, anyone, goo...",0,[],[]

## To trainable dataset

1. select useful columns
2. apply Bag of Word with TF-IDF (instead of word count) on "title", "selftext", and "comments"
3. create 3 separate BoW, each for "title", "selftext", and "comments"

In [26]:
trainable_dataset = tokenized_dataset[["no.Comments", "ups"]] # score column is same as ups, upratio is kind of wired because down is always 0, hence only no.Comments and ups are used
trainable_dataset

      no.Comments  ups
0              48  637
1              15  448
2              51  424
3              24  360
4              60  300
...           ...  ...
1909            3    4
1910            4    3
1911            4    5
1912            2    3
1913            1    3

[1914 rows x 2 columns]

In [27]:
from modules.vectorize import tf_idf_pd_serise, serise_to_BoW_dataframe
for text_column_name in ["title", "selftext", "merged_comments"]:
  scores = tf_idf_pd_serise(tokenized_dataset[text_column_name])
  bow = serise_to_BoW_dataframe(tokenized_dataset[text_column_name], scores, text_column_name + "_")
  trainable_dataset = pd.concat([trainable_dataset, bow], axis=1)
trainable_dataset

,no.Comments,ups,title_editing,title_kong,title_entire,title_normalize,title_attacker,title_stall,title_virtual,title_loop,...,merged_comments_lookup,merged_comments_14,merged_comments_thanks,merged_comments_numerical,merged_comments_cut,merged_comments_goto,merged_comments_cat,merged_comments_true,merged_comments_nah,merged_comments_first
0,48,637,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,15,448,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,51,424,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,24,360,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,60,300,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,3,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1910,4,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1911,4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1912,2,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1913,1,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
trainable_dataset = pd.concat([trainable_dataset, tokenized_dataset["tag"]], axis=1)
trainable_dataset

,no.Comments,ups,title_editing,title_kong,title_entire,title_normalize,title_attacker,title_stall,title_virtual,title_loop,...,merged_comments_14,merged_comments_thanks,merged_comments_numerical,merged_comments_cut,merged_comments_goto,merged_comments_cat,merged_comments_true,merged_comments_nah,merged_comments_first,tag
0,48,637,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,15,448,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,51,424,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,24,360,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,60,300,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,3,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1910,4,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1911,4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
1912,2,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
1913,1,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0

## Read and preprocess test dataset

## Training part